// <auto-generated>
#nullable enable

#pragma warning disable CS0649

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppArrayHandlers;

internal unsafe class NativeIl2CppArrayStructHandler_5_3_3 : INativeIl2CppArrayStructHandler
{
    public int Size => sizeof(Il2CppArray_5_3_3);

    private struct Il2CppArray_5_3_3
    {
        public Il2CppObject @base;
        public void* bounds;
        public int max_length;
    }

    public int GetLength(Il2CppArray* o)
    {
        var _ = (Il2CppArray_5_3_3*)o;
        return _->max_length;
    }

    public void SetLength(Il2CppArray* o, int value)
    {
        var _ = (Il2CppArray_5_3_3*)o;
        _->max_length = value;
    }
}
