// <auto-generated>

#nullable enable
#pragma warning disable CS0649

using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppArrayHandlers;

internal unsafe class NativeIl2CppArrayStructHandler_2017_2_0 : INativeIl2CppArrayStructHandler
{
    public int Size => sizeof(Il2CppArray_2017_2_0);

    private struct Il2CppArray_2017_2_0
    {
        public Il2CppObject @base;
        public void* bounds;
        public nuint max_length;
    }

    public int GetLength(Il2CppArray* o)
    {
        var _ = (Il2CppArray_2017_2_0*)o;
        return (int)_->max_length;
    }

    public void SetLength(Il2CppArray* o, int value)
    {
        var _ = (Il2CppArray_2017_2_0*)o;
        _->max_length = (nuint)value;
    }
}
