// <auto-generated>

#nullable enable

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppArrayHandlers;

public unsafe interface INativeIl2CppArrayStructHandler : INativeStructHandler
{
    public int GetLength(Il2CppArray* o);

    public void SetLength(Il2CppArray* o, int value);
}
