// <auto-generated>
#nullable enable

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppImageHandlers;

public unsafe interface INativeIl2CppImageStructHandler : INativeStructHandler
{
    public string? GetName(Il2CppImage* o);

    public void SetName(Il2CppImage* o, string? value);

    public ref byte* GetNamePointer(Il2CppImage* o);

    public Il2CppAssembly* GetAssembly(Il2CppImage* o);
}
