// <auto-generated>
#nullable enable

using Il2CppInterop.Bindings.Utilities;

namespace Il2CppInterop.Bindings.Structs;

[NativeStruct]
public unsafe partial struct Il2CppImage
{
    public static int Size => UnityVersionHandler.Il2CppImage.Size;

    public string? Name { get => UnityVersionHandler.Il2CppImage.GetName(Pointer); set => UnityVersionHandler.Il2CppImage.SetName(Pointer, value); }
    public ref byte* NamePointer => ref UnityVersionHandler.Il2CppImage.GetNamePointer(Pointer);

    public Il2CppAssembly* Assembly => UnityVersionHandler.Il2CppImage.GetAssembly(Pointer);
}
