// <auto-generated>

#nullable enable

using Il2CppInterop.Bindings.Utilities;

namespace Il2CppInterop.Bindings.Structs;

[NativeStruct]
public unsafe partial struct Il2CppArray
{
    public static int Size => UnityVersionHandler.Il2CppArray.Size;

    public int Length { get => UnityVersionHandler.Il2CppArray.GetLength(Pointer); set => UnityVersionHandler.Il2CppArray.SetLength(Pointer, value); }
}
