// <auto-generated>

#nullable enable

using Il2CppInterop.Bindings.Utilities;

namespace Il2CppInterop.Bindings.Structs;

[NativeStruct]
public unsafe partial struct Il2CppMethod
{
    public static int Size => UnityVersionHandler.Il2CppMethod.Size;

    public string? Name { get => UnityVersionHandler.Il2CppMethod.GetName(Pointer); set => UnityVersionHandler.Il2CppMethod.SetName(Pointer, value); }
    public ref byte* NamePointer => ref UnityVersionHandler.Il2CppMethod.GetNamePointer(Pointer);

    public uint Token { get => UnityVersionHandler.Il2CppMethod.GetToken(Pointer); set => UnityVersionHandler.Il2CppMethod.SetToken(Pointer, value); }
}
