// <auto-generated>

#nullable enable

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppException;

using Il2CppException = Il2CppInterop.Bindings.Structs.Il2CppException;

public unsafe interface INativeIl2CppExceptionStructHandler : INativeStructHandler
{
    public Il2CppObject* GetObject(Il2CppException* o);

    public Il2CppString* GetMessage(Il2CppException* o);

    public void SetMessage(Il2CppException* o, Il2CppString* value);

    public Il2CppString* GetStackTrace(Il2CppException* o);

    public void SetStackTrace(Il2CppException* o, Il2CppString* value);
}
