// <auto-generated>
#nullable enable

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppMethodHandlers;

public unsafe interface INativeIl2CppMethodStructHandler : INativeStructHandler
{
    public void* GetMethodPointer(Il2CppMethod* o);

    public void SetMethodPointer(Il2CppMethod* o, void* value);

    public Il2CppClass* GetClass(Il2CppMethod* o);

    public void SetClass(Il2CppMethod* o, Il2CppClass* value);

    public string? GetName(Il2CppMethod* o);

    public void SetName(Il2CppMethod* o, string? value);

    public ref byte* GetNamePointer(Il2CppMethod* o);

    public uint GetToken(Il2CppMethod* o);

    public void SetToken(Il2CppMethod* o, uint value);
}
