// <auto-generated>
#nullable enable

namespace Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppClassHandlers;

public unsafe interface INativeIl2CppClassStructHandler : INativeStructHandler
{
    public Il2CppImage* GetImage(Il2CppClass* o);

    public void SetImage(Il2CppClass* o, Il2CppImage* value);

    public string? GetName(Il2CppClass* o);

    public void SetName(Il2CppClass* o, string? value);

    public ref byte* GetNamePointer(Il2CppClass* o);

    public string? GetNamespace(Il2CppClass* o);

    public void SetNamespace(Il2CppClass* o, string? value);

    public ref byte* GetNamespacePointer(Il2CppClass* o);

    public Il2CppClass* GetDeclaringType(Il2CppClass* o);

    public void SetDeclaringType(Il2CppClass* o, Il2CppClass* value);

    public bool GetIsGeneric(Il2CppClass* o);

    public void SetIsGeneric(Il2CppClass* o, bool value);

    public bool GetIsSizeInitialized(Il2CppClass* o);

    public void SetIsSizeInitialized(Il2CppClass* o, bool value);

    public Il2CppType* GetByVal(Il2CppClass* o);

    public Il2CppClass* GetElementClass(Il2CppClass* o);

    public void SetElementClass(Il2CppClass* o, Il2CppClass* value);

    public Il2CppClass** GetNestedTypes(Il2CppClass* o);

    public void SetNestedTypes(Il2CppClass* o, Il2CppClass** value);

    public ushort GetNestedTypeCount(Il2CppClass* o);

    public void SetNestedTypeCount(Il2CppClass* o, ushort value);

    public Il2CppMethod** GetMethods(Il2CppClass* o);

    public void SetMethods(Il2CppClass* o, Il2CppMethod** value);

    public ushort GetMethodCount(Il2CppClass* o);

    public void SetMethodCount(Il2CppClass* o, ushort value);

    public Il2CppField* GetFields(Il2CppClass* o);

    public void SetFields(Il2CppClass* o, Il2CppField* value);

    public ushort GetFieldCount(Il2CppClass* o);

    public void SetFieldCount(Il2CppClass* o, ushort value);

    public uint GetInstanceSize(Il2CppClass* o);

    public void SetInstanceSize(Il2CppClass* o, uint value);

    public byte GetRank(Il2CppClass* o);

    public void SetRank(Il2CppClass* o, byte value);
}
