// <auto-generated>
#nullable enable

using System.Runtime.InteropServices;
using Il2CppInterop.Bindings.Structs;

namespace Il2CppInterop.Bindings;

internal static unsafe partial class Il2CppImports
{
    [ApplicableToUnityVersions("5.2.2", "2019.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_init")]
    public static partial void il2cpp_init_5_2_2([MarshalAs(UnmanagedType.LPUTF8Str)] string? domain_name);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_init")]
    public static partial int il2cpp_init_2019_1_0([MarshalAs(UnmanagedType.LPUTF8Str)] string? domain_name);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_shutdown();

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_config_dir([MarshalAs(UnmanagedType.LPUTF8Str)] string? config_path);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_data_dir([MarshalAs(UnmanagedType.LPUTF8Str)] string? data_path);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_commandline_arguments(int argc, [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPUTF8Str)] string?[] argv, [MarshalAs(UnmanagedType.LPUTF8Str)] string? basedir);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_memory_callbacks(Il2CppMemoryCallbacks* callbacks);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppImage* il2cpp_get_corlib();

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_add_internal_call([MarshalAs(UnmanagedType.LPUTF8Str)] string? name, void* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_resolve_icall([MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_alloc(nuint size);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_free(void* ptr);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_array_class_get(Il2CppClass* element_class, uint rank);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_array_length(Il2CppArray* array);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_array_get_byte_length(Il2CppArray* array);

    [ApplicableToUnityVersions("5.2.2", "2017.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_array_new")]
    public static partial Il2CppArray* il2cpp_array_new_5_2_2(Il2CppClass* elementTypeInfo, int length);

    [ApplicableToUnityVersions("2017.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_array_new")]
    public static partial Il2CppArray* il2cpp_array_new_2017_2_0(Il2CppClass* elementTypeInfo, nuint length);

    [ApplicableToUnityVersions("5.2.2", "2017.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_array_new_specific")]
    public static partial Il2CppArray* il2cpp_array_new_specific_5_2_2(Il2CppClass* arrayTypeInfo, int length);

    [ApplicableToUnityVersions("2017.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_array_new_specific")]
    public static partial Il2CppArray* il2cpp_array_new_specific_2017_2_0(Il2CppClass* arrayTypeInfo, nuint length);

    [ApplicableToUnityVersions("5.2.2", "2017.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_array_new_full")]
    public static partial Il2CppArray* il2cpp_array_new_full_5_2_2(Il2CppClass* array_class, int* lengths, int* lower_bounds);

    [ApplicableToUnityVersions("2017.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_array_new_full")]
    public static partial Il2CppArray* il2cpp_array_new_full_2017_2_0(Il2CppClass* array_class, nuint* lengths, nuint* lower_bounds);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_bounded_array_class_get(Il2CppClass* element_class, uint rank, [MarshalAs(UnmanagedType.U1)] bool bounded);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_array_element_size(Il2CppClass* array_class);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppImage* il2cpp_assembly_get_image(Il2CppAssembly* assembly);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppType* il2cpp_class_enum_basetype(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_generic(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_inflated(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_assignable_from(Il2CppClass* klass, Il2CppClass* oklass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_subclass_of(Il2CppClass* klass, Il2CppClass* klassc, [MarshalAs(UnmanagedType.U1)] bool check_interfaces);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_has_parent(Il2CppClass* klass, Il2CppClass* klassc);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_from_il2cpp_type(Il2CppType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_from_name(Il2CppImage* image, [MarshalAs(UnmanagedType.LPUTF8Str)] string? namespaze, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_from_system_type(Il2CppReflectionType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_get_element_class(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppEvent* il2cpp_class_get_events(Il2CppClass* klass, void** iter);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppField* il2cpp_class_get_fields(Il2CppClass* klass, void** iter);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_get_interfaces(Il2CppClass* klass, void** iter);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppProperty* il2cpp_class_get_properties(Il2CppClass* klass, void** iter);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppProperty* il2cpp_class_get_property_from_name(Il2CppClass* klass, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppField* il2cpp_class_get_field_from_name(Il2CppClass* klass, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_class_get_methods(Il2CppClass* klass, void** iter);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_class_get_method_from_name(Il2CppClass* klass, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name, int argsCount);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_class_get_name(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_class_get_namespace(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_get_parent(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_get_declaring_type(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_class_instance_size(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial nuint il2cpp_class_num_fields(Il2CppClass* enumKlass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_valuetype(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_class_value_size(Il2CppClass* klass, uint* align);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_class_get_flags(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_abstract(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_interface(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_class_array_element_size(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_from_type(Il2CppType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppType* il2cpp_class_get_type(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_has_attribute(Il2CppClass* klass, Il2CppClass* attr_class);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_has_references(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_enum(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppImage* il2cpp_class_get_image(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_class_get_assemblyname(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial nuint il2cpp_class_get_bitmap_size(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_class_get_bitmap(Il2CppClass* klass, nuint* bitmap);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_stats_dump_to_file([MarshalAs(UnmanagedType.LPUTF8Str)] string? path);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial ulong il2cpp_stats_get_value(uint stat);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppDomain* il2cpp_domain_get();

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppAssembly* il2cpp_domain_assembly_open(Il2CppDomain* domain, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppAssembly** il2cpp_domain_get_assemblies(Il2CppDomain* domain, nuint* size);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_raise_exception(Il2CppException* ex);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppException* il2cpp_exception_from_name_msg(Il2CppImage* image, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name_space, [MarshalAs(UnmanagedType.LPUTF8Str)] string? name, [MarshalAs(UnmanagedType.LPUTF8Str)] string? msg);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppException* il2cpp_get_exception_argument_null([MarshalAs(UnmanagedType.LPUTF8Str)] string? arg);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_format_exception(Il2CppException* ex, byte* message, int message_size);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_format_stack_trace(Il2CppException* ex, byte* output, int output_size);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unhandled_exception(Il2CppException* ex);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_field_get_flags(Il2CppField* field);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_field_get_name(Il2CppField* field);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_field_get_parent(Il2CppField* field);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial nuint il2cpp_field_get_offset(Il2CppField* field);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppType* il2cpp_field_get_type(Il2CppField* field);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_field_get_value(Il2CppObject* obj, Il2CppField* field, void* value);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_field_get_value_object(Il2CppField* field, Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_field_has_attribute(Il2CppField* field, Il2CppClass* attr_class);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_field_set_value(Il2CppObject* obj, Il2CppField* field, void* value);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_field_static_get_value(Il2CppField* field, void* value);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_field_static_set_value(Il2CppField* field, void* value);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_collect(int maxGenerations);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial long il2cpp_gc_get_used_size();

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial long il2cpp_gc_get_heap_size();

    [ApplicableToUnityVersions("5.2.2", "2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_new")]
    public static partial uint il2cpp_gchandle_new_5_2_2(Il2CppObject* obj, [MarshalAs(UnmanagedType.U1)] bool pinned);

    [ApplicableToUnityVersions("2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_new")]
    public static partial void* il2cpp_gchandle_new_2023_1_0(Il2CppObject* obj, [MarshalAs(UnmanagedType.U1)] bool pinned);

    [ApplicableToUnityVersions("5.2.2", "2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_new_weakref")]
    public static partial uint il2cpp_gchandle_new_weakref_5_2_2(Il2CppObject* obj, [MarshalAs(UnmanagedType.U1)] bool track_resurrection);

    [ApplicableToUnityVersions("2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_new_weakref")]
    public static partial void* il2cpp_gchandle_new_weakref_2023_1_0(Il2CppObject* obj, [MarshalAs(UnmanagedType.U1)] bool track_resurrection);

    [ApplicableToUnityVersions("5.2.2", "2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_get_target")]
    public static partial Il2CppObject* il2cpp_gchandle_get_target_5_2_2(uint gchandle);

    [ApplicableToUnityVersions("2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_get_target")]
    public static partial Il2CppObject* il2cpp_gchandle_get_target_2023_1_0(void* gchandle);

    [ApplicableToUnityVersions("5.2.2", "2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_free")]
    public static partial void il2cpp_gchandle_free_5_2_2(uint gchandle);

    [ApplicableToUnityVersions("2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_gchandle_free")]
    public static partial void il2cpp_gchandle_free_2023_1_0(void* gchandle);

    [ApplicableToUnityVersions("5.2.2", "2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_unity_liveness_calculation_begin(Il2CppClass* filter, int max_object_count, void* callback, void* userdata, void* onWorldStarted, void* onWorldStopped);

    [ApplicableToUnityVersions("5.2.2", "2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unity_liveness_calculation_end(void* state);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unity_liveness_calculation_from_root(Il2CppObject* root, void* state);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unity_liveness_calculation_from_statics(void* state);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppType* il2cpp_method_get_return_type(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_method_get_declaring_type(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_method_get_name(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppReflectionMethod* il2cpp_method_get_object(Il2CppMethod* method, Il2CppClass* refclass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_method_is_generic(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_method_is_inflated(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_method_is_instance(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_method_get_param_count(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppType* il2cpp_method_get_param(Il2CppMethod* method, uint index);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_method_get_class(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_method_has_attribute(Il2CppMethod* method, Il2CppClass* attr_class);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_method_get_flags(Il2CppMethod* method, uint* iflags);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_method_get_token(Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_method_get_param_name(Il2CppMethod* method, uint index);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_install(Il2CppProfiler* prof, void* shutdown_callback);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_set_events(uint events);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_install_enter_leave(void* enter, void* fleave);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_install_allocation(void* callback);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_install_gc(void* callback, void* heap_resize_callback);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_property_get_flags(Il2CppProperty* prop);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_property_get_get_method(Il2CppProperty* prop);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_property_get_set_method(Il2CppProperty* prop);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_property_get_name(Il2CppProperty* prop);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_property_get_parent(Il2CppProperty* prop);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_object_get_class(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_object_get_size(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_object_get_virtual_method(Il2CppObject* obj, Il2CppMethod* method);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_object_new(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_object_unbox(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_value_box(Il2CppClass* klass, void* data);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_monitor_enter(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_monitor_try_enter(Il2CppObject* obj, uint timeout);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_monitor_exit(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_monitor_pulse(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_monitor_pulse_all(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_monitor_wait(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_monitor_try_wait(Il2CppObject* obj, uint timeout);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_runtime_invoke(Il2CppMethod* method, void* obj, void** @params, Il2CppException** exc);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_runtime_invoke_convert_args(Il2CppMethod* method, void* obj, Il2CppObject** @params, int paramCount, Il2CppException** exc);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_runtime_class_init(Il2CppClass* klass);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_runtime_object_init(Il2CppObject* obj);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_runtime_object_init_exception(Il2CppObject* obj, Il2CppException** exc);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_runtime_unhandled_exception_policy_set(uint value);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_string_length(Il2CppString* str);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial char* il2cpp_string_chars(Il2CppString* str);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppString* il2cpp_string_new([MarshalAs(UnmanagedType.LPUTF8Str)] string? str);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppString* il2cpp_string_new_len([MarshalAs(UnmanagedType.LPUTF8Str)] string? str, uint length);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppString* il2cpp_string_new_utf16([MarshalAs(UnmanagedType.LPWStr)] string? text, int len);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppString* il2cpp_string_new_wrapper([MarshalAs(UnmanagedType.LPUTF8Str)] string? str);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppString* il2cpp_string_intern(Il2CppString* str);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppString* il2cpp_string_is_interned(Il2CppString* str);

    [ApplicableToUnityVersions("5.2.2", "2018.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_thread_get_name(Il2CppThread* thread, uint* len);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppThread* il2cpp_thread_current();

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppThread* il2cpp_thread_attach(Il2CppDomain* domain);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_thread_detach(Il2CppThread* thread);

    [ApplicableToUnityVersions("5.2.2", "2023.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppThread** il2cpp_thread_get_all_attached_threads(nuint* size);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_is_vm_thread(Il2CppThread* thread);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_current_thread_walk_frame_stack(void* func, void* user_data);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_thread_walk_frame_stack(Il2CppThread* thread, void* func, void* user_data);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_current_thread_get_top_frame(Il2CppStackFrameInfo* frame);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_thread_get_top_frame(Il2CppThread* thread, Il2CppStackFrameInfo* frame);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_current_thread_get_frame_at(int offset, Il2CppStackFrameInfo* frame);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_thread_get_frame_at(Il2CppThread* thread, int offset, Il2CppStackFrameInfo* frame);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_current_thread_get_stack_depth();

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_thread_get_stack_depth(Il2CppThread* thread);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_type_get_object(Il2CppType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_type_get_type(Il2CppType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_type_get_class_or_element_class(Il2CppType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_type_get_name(Il2CppType* type);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppAssembly* il2cpp_image_get_assembly(Il2CppImage* image);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_image_get_name(Il2CppImage* image);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_image_get_filename(Il2CppImage* image);

    [ApplicableToUnityVersions("5.2.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_image_get_entry_point(Il2CppImage* image);

    [ApplicableToUnityVersions("5.2.4", "5.3.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_set_find_plugin_callback")]
    public static partial void il2cpp_set_find_plugin_callback_5_2_4(void* method);

    [ApplicableToUnityVersions("5.3.1")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_set_find_plugin_callback")]
    public static partial void il2cpp_set_find_plugin_callback_5_3_1(void* method);

    [ApplicableToUnityVersions("5.3.2")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_class_get_nested_types(Il2CppClass* klass, void** iter);

    [ApplicableToUnityVersions("5.3.5")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_gc_collect_a_little();

    [ApplicableToUnityVersions("5.3.5")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_disable();

    [ApplicableToUnityVersions("5.3.5")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_enable();

    [ApplicableToUnityVersions("5.5.0", "2019.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_init_utf16")]
    public static partial void il2cpp_init_utf16_5_5_0([MarshalAs(UnmanagedType.LPWStr)] string? domain_name);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_init_utf16")]
    public static partial int il2cpp_init_utf16_2019_1_0([MarshalAs(UnmanagedType.LPWStr)] string? domain_name);

    [ApplicableToUnityVersions("5.5.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_commandline_arguments_utf16(int argc, [MarshalAs(UnmanagedType.LPArray, ArraySubType = UnmanagedType.LPWStr)] string?[] argv, [MarshalAs(UnmanagedType.LPUTF8Str)] string? basedir);

    [ApplicableToUnityVersions("5.5.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_config_utf16([MarshalAs(UnmanagedType.LPWStr)] string? executablePath);

    [ApplicableToUnityVersions("5.5.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_config([MarshalAs(UnmanagedType.LPUTF8Str)] string? executablePath);

    [ApplicableToUnityVersions("5.6.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_field_set_value_object(Il2CppObject* instance, Il2CppField* field, Il2CppObject* value);

    [ApplicableToUnityVersions("5.6.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_register_log_callback(void* method);

    [ApplicableToUnityVersions("2017.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_temp_dir([MarshalAs(UnmanagedType.LPUTF8Str)] string? temp_path);

    [ApplicableToUnityVersions("2017.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_blittable(Il2CppClass* klass);

    [ApplicableToUnityVersions("2017.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_install_fileio(void* callback);

    [ApplicableToUnityVersions("2018.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_class_get_type_token(Il2CppClass* klass);

    [ApplicableToUnityVersions("2018.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_class_get_rank(Il2CppClass* klass);

    [ApplicableToUnityVersions("2018.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_type_is_byref(Il2CppType* type);

    [ApplicableToUnityVersions("2018.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_type_equals(Il2CppType* type, Il2CppType* otherType);

    [ApplicableToUnityVersions("2018.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_debugger_set_agent_options([MarshalAs(UnmanagedType.LPUTF8Str)] string? options);

    [ApplicableToUnityVersions("2018.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppMethod* il2cpp_method_get_from_reflection(Il2CppReflectionMethod* method);

    [ApplicableToUnityVersions("2018.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_type_get_attrs(Il2CppType* type);

    [ApplicableToUnityVersions("2018.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_type_get_assembly_qualified_name(Il2CppType* type);

    [ApplicableToUnityVersions("2018.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_is_debugger_attached();

    [ApplicableToUnityVersions("2018.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unity_install_unitytls_interface(void* unitytlsInterfaceStruct);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_gc_is_disabled();

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_wbarrier_set_field(Il2CppObject* obj, void** targetAddress, void* @object);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_profiler_install_thread(void* start, void* end);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial nuint il2cpp_image_get_class_count(Il2CppImage* image);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppClass* il2cpp_image_get_class(Il2CppImage* image, nuint index);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppCustomAttrInfo* il2cpp_custom_attrs_from_class(Il2CppClass* klass);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppCustomAttrInfo* il2cpp_custom_attrs_from_method(Il2CppMethod* method);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppObject* il2cpp_custom_attrs_get_attr(Il2CppCustomAttrInfo* ainfo, Il2CppClass* attr_klass);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_custom_attrs_has_attr(Il2CppCustomAttrInfo* ainfo, Il2CppClass* attr_klass);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppArray* il2cpp_custom_attrs_construct(Il2CppCustomAttrInfo* cinfo);

    [ApplicableToUnityVersions("2018.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_custom_attrs_free(Il2CppCustomAttrInfo* ainfo);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial long il2cpp_gc_get_max_time_slice_ns();

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_set_max_time_slice_ns(long maxTimeSlice);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_gc_is_incremental();

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_gc_has_strict_wbarriers();

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_set_external_allocation_tracker(void* func);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_set_external_wbarrier_tracker(void* func);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_class_set_userdata(Il2CppClass* klass, void* userdata);

    [ApplicableToUnityVersions("2019.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial int il2cpp_class_get_userdata_offset();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_class_for_each(void* klassReportFunc, void* userData);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_type_get_name_chunked(Il2CppType* type, void* chunkReportFunc, void* userData);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_class_get_data_size(Il2CppClass* klass);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_class_get_static_field_data(Il2CppClass* klass);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_field_is_literal(Il2CppField* field);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_foreach_heap(void* func, void* userData);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_stop_gc_world();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_start_gc_world();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gchandle_foreach_get_target(void* func, void* userData);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_object_header_size();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_array_object_header_size();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_offset_of_array_length_in_array_object_header();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_offset_of_array_bounds_in_array_object_header();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial uint il2cpp_allocation_granularity();

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_override_stack_backtrace(void* stackBacktraceFunc);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_type_is_static(Il2CppType* type);

    [ApplicableToUnityVersions("2019.3.0")]
    [LibraryImportAttribute("GameAssembly")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_type_is_pointer_type(Il2CppType* type);

    [ApplicableToUnityVersions("2019.4.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_set_default_thread_affinity(long affinity_mask);

    [ApplicableToUnityVersions("2020.1.0", "2021.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_native_stack_trace")]
    public static partial void il2cpp_native_stack_trace_2020_1_0(Il2CppException* ex, nuint** addresses, int* numFrames, [MarshalAs(UnmanagedType.LPUTF8Str)] string? imageUUID);

    [ApplicableToUnityVersions("2021.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_native_stack_trace")]
    public static partial void il2cpp_native_stack_trace_2021_2_0(Il2CppException* ex, nuint** addresses, int* numFrames, [MarshalAs(UnmanagedType.LPUTF8Str)] string? imageUUID, [MarshalAs(UnmanagedType.LPUTF8Str)] string? imageName);

    [ApplicableToUnityVersions("2020.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_start_incremental_collection();

    [ApplicableToUnityVersions("2020.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_set_mode(uint mode);

    [ApplicableToUnityVersions("2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_gc_alloc_fixed(nuint size);

    [ApplicableToUnityVersions("2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_gc_free_fixed(void* address);

    [ApplicableToUnityVersions("2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void* il2cpp_unity_liveness_allocate_struct(Il2CppClass* filter, int max_object_count, void* callback, void* userdata, void* reallocate);

    [ApplicableToUnityVersions("2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unity_liveness_finalize(void* state);

    [ApplicableToUnityVersions("2021.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial void il2cpp_unity_liveness_free_struct(void* state);

    [ApplicableToUnityVersions("2021.3.20", "2022.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_unity_set_android_network_up_state_func")]
    public static partial void il2cpp_unity_set_android_network_up_state_func_2021_3_20(void* func);

    [ApplicableToUnityVersions("2022.2.9")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_unity_set_android_network_up_state_func")]
    public static partial void il2cpp_unity_set_android_network_up_state_func_2022_2_9(void* func);

    [ApplicableToUnityVersions("2022.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial byte* il2cpp_type_get_reflection_name(Il2CppType* type);

    [ApplicableToUnityVersions("2022.2.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppCustomAttrInfo* il2cpp_custom_attrs_from_field(Il2CppField* field);

    [ApplicableToUnityVersions("2022.2.19", "2023.1.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_class_is_inited")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_inited_2022_2_19(Il2CppClass* klass);

    [ApplicableToUnityVersions("2023.2.0")]
    [LibraryImportAttribute("GameAssembly", EntryPoint = "il2cpp_class_is_inited")]
    [return: MarshalAs(UnmanagedType.U1)]
    public static partial bool il2cpp_class_is_inited_2023_2_0(Il2CppClass* klass);

    [ApplicableToUnityVersions("2023.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppField* il2cpp_field_get_from_reflection(Il2CppReflectionField* field);

    [ApplicableToUnityVersions("2023.1.0")]
    [LibraryImportAttribute("GameAssembly")]
    public static partial Il2CppReflectionField* il2cpp_field_get_object(Il2CppField* field, Il2CppClass* refclass);
}
