// <auto-generated>

using AssetRipper.VersionUtilities;
using Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppClass;

namespace Il2CppInterop.Bindings;

public static partial class UnityVersionHandler
{
    public static INativeIl2CppClassStructHandler Il2CppClass { get; private set; }

    private static void InitializeNativeStructHandlers(UnityVersion unityVersion)
    {
        if (unityVersion >= new UnityVersion(2022, 2, 0, UnityVersionType.Alpha, 9)) Il2CppClass = new NativeIl2CppClassStructHandler_2022_2_0_A9();
        else if (unityVersion >= new UnityVersion(2021, 2, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2021_2_0();
        else if (unityVersion >= new UnityVersion(2021, 1, 24)) Il2CppClass = new NativeIl2CppClassStructHandler_2021_1_24();
        else if (unityVersion >= new UnityVersion(2021, 1, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2021_1_0();
        else if (unityVersion >= new UnityVersion(2020, 3, 20)) Il2CppClass = new NativeIl2CppClassStructHandler_2020_3_20();
        else if (unityVersion >= new UnityVersion(2020, 2, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2020_2_0();
        else if (unityVersion >= new UnityVersion(2019, 1, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2019_1_0();
        else if (unityVersion >= new UnityVersion(2018, 3, 8)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_3_8();
        else if (unityVersion >= new UnityVersion(2018, 3, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_3_0();
        else if (unityVersion >= new UnityVersion(2018, 2, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_2_0();
        else if (unityVersion >= new UnityVersion(2018, 1, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_1_0();
        else if (unityVersion >= new UnityVersion(5, 6, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_5_6_0();
        else if (unityVersion >= new UnityVersion(5, 5, 1)) Il2CppClass = new NativeIl2CppClassStructHandler_5_5_1();
        else if (unityVersion >= new UnityVersion(5, 5, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_5_5_0();
        else if (unityVersion >= new UnityVersion(5, 4, 4)) Il2CppClass = new NativeIl2CppClassStructHandler_5_4_4();
        else if (unityVersion >= new UnityVersion(5, 3, 6)) Il2CppClass = new NativeIl2CppClassStructHandler_5_3_6();
        else if (unityVersion >= new UnityVersion(5, 3, 3)) Il2CppClass = new NativeIl2CppClassStructHandler_5_3_3();
        else if (unityVersion >= new UnityVersion(5, 3, 2)) Il2CppClass = new NativeIl2CppClassStructHandler_5_3_2();
        else if (unityVersion >= new UnityVersion(5, 2, 2)) Il2CppClass = new NativeIl2CppClassStructHandler_5_2_2();
    }
}
