// <auto-generated>

using AssetRipper.VersionUtilities;
using Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppClassHandlers;
using Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppMethodHandlers;
using Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppExceptionHandlers;
using Il2CppInterop.Bindings.Structs.VersionSpecific.Il2CppArrayHandlers;

namespace Il2CppInterop.Bindings;

public static partial class UnityVersionHandler
{
    public static INativeIl2CppClassStructHandler Il2CppClass { get; private set; }
    public static INativeIl2CppMethodStructHandler Il2CppMethod { get; private set; }
    public static INativeIl2CppExceptionStructHandler Il2CppException { get; private set; }
    public static INativeIl2CppArrayStructHandler Il2CppArray { get; private set; }

    private static void InitializeNativeStructHandlers(UnityVersion unityVersion)
    {
        if (unityVersion >= new UnityVersion(2022, 2, 0, UnityVersionType.Alpha, 9)) Il2CppClass = new NativeIl2CppClassStructHandler_2022_2_0_A9();
        else if (unityVersion >= new UnityVersion(2021, 2, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2021_2_0();
        else if (unityVersion >= new UnityVersion(2021, 1, 24)) Il2CppClass = new NativeIl2CppClassStructHandler_2021_1_24();
        else if (unityVersion >= new UnityVersion(2021, 1, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2021_1_0();
        else if (unityVersion >= new UnityVersion(2020, 3, 20)) Il2CppClass = new NativeIl2CppClassStructHandler_2020_3_20();
        else if (unityVersion >= new UnityVersion(2020, 2, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2020_2_0();
        else if (unityVersion >= new UnityVersion(2019, 1, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2019_1_0();
        else if (unityVersion >= new UnityVersion(2018, 3, 8)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_3_8();
        else if (unityVersion >= new UnityVersion(2018, 3, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_3_0();
        else if (unityVersion >= new UnityVersion(2018, 2, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_2_0();
        else if (unityVersion >= new UnityVersion(2018, 1, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_2018_1_0();
        else if (unityVersion >= new UnityVersion(5, 6, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_5_6_0();
        else if (unityVersion >= new UnityVersion(5, 5, 1)) Il2CppClass = new NativeIl2CppClassStructHandler_5_5_1();
        else if (unityVersion >= new UnityVersion(5, 5, 0)) Il2CppClass = new NativeIl2CppClassStructHandler_5_5_0();
        else if (unityVersion >= new UnityVersion(5, 4, 4)) Il2CppClass = new NativeIl2CppClassStructHandler_5_4_4();
        else if (unityVersion >= new UnityVersion(5, 3, 6)) Il2CppClass = new NativeIl2CppClassStructHandler_5_3_6();
        else if (unityVersion >= new UnityVersion(5, 3, 3)) Il2CppClass = new NativeIl2CppClassStructHandler_5_3_3();
        else if (unityVersion >= new UnityVersion(5, 3, 2)) Il2CppClass = new NativeIl2CppClassStructHandler_5_3_2();
        else if (unityVersion >= new UnityVersion(5, 2, 2)) Il2CppClass = new NativeIl2CppClassStructHandler_5_2_2();

        if (unityVersion >= new UnityVersion(2022, 1, 0, UnityVersionType.Beta, 7)) Il2CppMethod = new NativeIl2CppMethodStructHandler_2022_1_0_B7();
        else if (unityVersion >= new UnityVersion(2021, 2, 0)) Il2CppMethod = new NativeIl2CppMethodStructHandler_2021_2_0();
        else if (unityVersion >= new UnityVersion(2018, 3, 0)) Il2CppMethod = new NativeIl2CppMethodStructHandler_2018_3_0();
        else if (unityVersion >= new UnityVersion(2018, 1, 0)) Il2CppMethod = new NativeIl2CppMethodStructHandler_2018_1_0();
        else if (unityVersion >= new UnityVersion(5, 3, 6)) Il2CppMethod = new NativeIl2CppMethodStructHandler_5_3_6();
        else if (unityVersion >= new UnityVersion(5, 2, 2)) Il2CppMethod = new NativeIl2CppMethodStructHandler_5_2_2();

        if (unityVersion >= new UnityVersion(2021, 2, 0)) Il2CppException = new NativeIl2CppExceptionStructHandler_2021_2_0();
        else if (unityVersion >= new UnityVersion(2019, 3, 0)) Il2CppException = new NativeIl2CppExceptionStructHandler_2019_3_0();
        else if (unityVersion >= new UnityVersion(5, 6, 0)) Il2CppException = new NativeIl2CppExceptionStructHandler_5_6_0();
        else if (unityVersion >= new UnityVersion(5, 3, 5)) Il2CppException = new NativeIl2CppExceptionStructHandler_5_3_5();
        else if (unityVersion >= new UnityVersion(5, 2, 2)) Il2CppException = new NativeIl2CppExceptionStructHandler_5_2_2();

        if (unityVersion >= new UnityVersion(2017, 2, 0)) Il2CppArray = new NativeIl2CppArrayStructHandler_2017_2_0();
        else if (unityVersion >= new UnityVersion(5, 3, 3)) Il2CppArray = new NativeIl2CppArrayStructHandler_5_3_3();
        else if (unityVersion >= new UnityVersion(5, 2, 2)) Il2CppArray = new NativeIl2CppArrayStructHandler_5_2_2();
    }
}
