name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - uses: actions/cache@v3
        with:
          path: ./Il2CppInterop.Bindings.Generator/bin/libil2cpp-source
          key: libil2cpp-source-${{ hashFiles('./Il2CppInterop.Bindings.Generator/UnityVersions.txt') }}
          restore-keys: |
            libil2cpp-source-

      - name: Ensure Il2CppInterop.Bindings was re-generated
        run: |
          sudo apt install libtinfo5 # https://github.com/MochiLibraries/ClangSharp.Pathogen/issues/4#issuecomment-981082307
          dotnet run -c Release --project ./Il2CppInterop.Bindings.Generator
          if [[ $(git status --porcelain) ]]; then git diff; exit 1; fi
