name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - uses: actions/cache@v4
        with:
          path: ./Il2CppInterop.Bindings.Generator/bin/libil2cpp-source
          key: libil2cpp-source-${{ hashFiles('./Il2CppInterop.Bindings.Generator/UnityVersions.txt') }}
          restore-keys: |
            libil2cpp-source-

      - name: Ensure Il2CppInterop.Bindings was re-generated
        run: |
          dotnet run -c Release --project ./Il2CppInterop.Bindings.Generator
          if [[ $(git status --porcelain) ]]; then git --no-pager diff; exit 1; fi
